**AIM:**
    To implement and verify the XOR logic function using a Feed Forward Neural Network.

In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_der(x):
    return x * (1 - x)


In [3]:
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

In [4]:
np.random.seed(1)

w1 = np.random.rand(2, 2)   
b1 = np.random.rand(1, 2)

w2 = np.random.rand(2, 1)   
b2 = np.random.rand(1, 1)


In [7]:
lr = 0.5
epochs = 5000


**FEED FORWARD ALGORITHM**

In [8]:
for epoch in range(epochs):

    # Feed forward pass
    hidden_in = np.dot(x, w1) + b1
    hidden_out = sigmoid(hidden_in)

    final_in = np.dot(hidden_out, w2) + b2
    output = sigmoid(final_in)

    # Error calculation
    error = y - output

    d_out = error * sigmoid_der(output)
    d_hidden = np.dot(d_out, w2.T) * sigmoid_der(hidden_out)

    # Weight and bias updates
    w2 += lr * np.dot(hidden_out.T, d_out)
    b2 += lr * np.sum(d_out, axis=0, keepdims=True)

    w1 += lr * np.dot(x.T, d_hidden)
    b1 += lr * np.sum(d_hidden, axis=0, keepdims=True)

    # Displaying loss
    if epoch % 1000 == 0:
        loss = np.mean(error ** 2)
        print(f"Epoch {epoch}, Loss: {loss:.6f}")


Epoch 0, Loss: 0.003788
Epoch 1000, Loss: 0.001650
Epoch 2000, Loss: 0.001034
Epoch 3000, Loss: 0.000747
Epoch 4000, Loss: 0.000583


In [10]:
print("\nFinal Weights and Biases:")
print("\nWeights (Input → Hidden):\n", w1)
print("\nBias (Hidden Layer):\n", b1)
print("\nWeights (Hidden → Output):\n", w2)
print("\nBias (Output Layer):\n", b2)



Final Weights and Biases:

Weights (Input → Hidden):
 [[4.42190089 6.38069025]
 [4.41365347 6.34550045]]

Bias (Hidden Layer):
 [[-6.78172235 -2.80873047]]

Weights (Hidden → Output):
 [[-9.89211585]
 [ 9.17580109]]

Bias (Output Layer):
 [[-4.21856537]]


In [11]:
print("\nFeed Forward Network Output (Raw Values):")
for i in range(len(x)):
    print(x[i], "->", output[i][0])



Feed Forward Network Output (Raw Values):
[0 0] -> 0.023939385794301635
[0 1] -> 0.9791728531399109
[1 0] -> 0.9792200792953013
[1 1] -> 0.0216504350305581


**XOR AFTER TRAINING**

In [12]:
print("\nFinal XOR Output:")
for i in range(len(x)):
    print(x[i], "->", int(output[i][0] > 0.5))



Final XOR Output:
[0 0] -> 0
[0 1] -> 1
[1 0] -> 1
[1 1] -> 0


**RESULT:**
The Feed Forward Neural Network was successfully trained to implement the XOR logic function. The obtained outputs matched the XOR truth table, proving that the feed forward network can solve non-linearly separable problems.